---
dataset_name: "bloodmnist"
num_classes: 8
num_channels: 3
batch_size: 4
epochs_per_round: 4
lda_concentration: .inf
num_clients_per_round: 10
num_total_clients: 100
num_rounds: 200
root_dir: "./data"
cpus_per_client: 1
gpus_per_client: 0
hydra.job.chdir: False
is_simulation: True

gen_federated_partitions:
  _target_: medicalmnist.utils.gen_partitions
  dataset_name: ${dataset_name}
  num_total_clients: ${num_total_clients}
  lda_concentration: ${lda_concentration}

get_initial_parameters:
  _target_: medicalmnist.utils.get_initial_parameters
  num_classes: ${num_classes}
  num_channels: ${num_channels}

get_eval_fn:
  _target_: medicalmnist.utils.get_eval_fn
  dataset_name: ${dataset_name}
  num_classes: ${num_classes}
  num_channels: ${num_channels}

gen_on_fit_config_fn:
  _target_: medicalmnist.utils.gen_on_fit_config_fn
  epochs_per_round: ${epochs_per_round}
  batch_size: ${batch_size}

plot_results:
  _target_: medicalmnist.utils.plot_metric_from_history
  dataset_name: ${dataset_name}
  strategy_name: ${strategy.name}
  expected_maximum: ${strategy.expected_accuracy}
  save_plot_path: ./${dataset_name}_${strategy.name}.png

get_ray_client_fn:
  _target_: medicalmnist.client.get_ray_client_fn
  fed_dir: None
  num_classes: ${num_classes}
  num_channels: ${num_channels}

ray_config:
  include_dashboard: False

defaults:
  - _self_
  - strategy: "fedavg"
